name: Lint

on:
  push:
  pull_request:

jobs:
  csharpier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Use your project's version

      - run: dotnet tool restore
      - run: dotnet csharpier check .