name: Update Packages

on: 
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  metadata:
    name: Update Win32Metadata
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git User
        shell: pwsh
        run: |
          git config --local user.email 'holy-tao@users.noreply.github.com'
          git config --local user.name '🤖 Tao Beloney'

          git config --local push.autoSetupRemote true
          git config --local push.default upstream

      - name: Download Win32Metadata
        shell: pwsh
        run: ./scripts/Get-Win32Metadata.ps1

      - name: Commit Changes
        id: commit-metadata
        shell: pwsh
        run: |
          $version = (Get-Content ./metadata/Microsoft.Windows.SDK.Win32Metadata.version -Raw).Trim()
          $branchName = "update-win32metadata-$version"

          git add ./metadata/*.winmd
          git add ./metadata/*.version

          if (-not (git diff-index --quiet HEAD --)) {
              git commit -m "Update Win32Metadata to $version"
          } else {
              Write-Host "No changes to commit for Win32Metadata"
              exit 0
          }

          Write-Host "version=$version"
          Write-Host "branchName=$branchName"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "branchName=$branchName"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "version=$version"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit-metadata.outputs.branchName }}
          title: "Update Win32Metadata to ${{ steps.commit-metadata.outputs.version }}"
          body: | 
            This PR updates Win32Metadata to version ${{ steps.commit-metadata.outputs.version }}.
            See https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/
          base: main
          labels: automated
          draft: false

  docs:
    name: Update Win32Docs
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git User
        shell: pwsh
        run: |
          git config --local user.email 'holy-tao@users.noreply.github.com'
          git config --local user.name '🤖 Tao Beloney'

          git config --local push.autoSetupRemote true
          git config --local push.default upstream

      - name: Download Win32Docs
        shell: pwsh
        run: ./scripts/Get-Win32Docs.ps1

      - name: Commit Changes
        id: commit-docs
        shell: pwsh
        run: |
          $version = (Get-Content ./metadata/Microsoft.Windows.SDK.Win32Docs.version -Raw).Trim()
          $branchName = "update-win32docs-$version"

          git add ./metadata/*.msgpack
          git add ./metadata/*.version

          if (-not (git diff-index --quiet HEAD --)) {
              git checkout -B $branchName
              git commit -m "Update Win32Docs to $version"
          } else {
              Write-Host "No changes to commit for Win32Docs"
              exit 0
          }

          Write-Host "version=$version"
          Write-Host "branchName=$branchName"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "branchName=$branchName"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "version=$version"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.commit-docs.outputs.branchName }}
          title: "Update Win32Docs to ${{ steps.commit-docs.outputs.version }}"
          body: |
            This PR updates Win32Docs to version ${{ steps.commit-docs.outputs.version }}.
            See https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Docs/
          base: main
          labels: automated
          draft: false
