name: Update Packages

on: 
  workflow_dispatch:
  workflow_call:
    outputs:
      metadata-version:
        description: 'The new version of the win32 metadata package'
        value: ${{ jobs.metadata.outputs.version }}
      apidocs-version:
        description: 'The new version of the win32 apidocs package'
        value: ${{ jobs.docs.outputs.version }}
      did-update:
        description: 'Whether any packages were updated'
        value: ${{ jobs.metadata.outputs.did-update || jobs.docs.outputs.did-update }}

permissions:
  contents: write

jobs:
  metadata:
    name: Update Win32Metadata
    runs-on: windows-latest
    outputs:
      version: ${{ steps.commit-metadata.outputs.version }}
      did-update: ${{ steps.commit-metadata.outputs.did-update }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        shell: pwsh
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git config --local push.autoSetupRemote true
          git config --local push.default upstream

      - name: Download Win32Metadata
        shell: pwsh
        run: ./scripts/Get-Win32Metadata.ps1

      - name: Commit and Push Changes
        id: commit-metadata
        shell: pwsh
        run: |
          $version = (Get-Content ./metadata/Microsoft.Windows.SDK.Win32Metadata.version -Raw).Trim()
          $branchName = "update-win32metadata-$version"

          Write-Output "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

          git add ./metadata/*.winmd
          git add ./metadata/*.version

          if (-not (git diff-index --quiet HEAD --)) {
              Write-Output "did-update=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

              git commit -m "Update Win32Metadata to $version"
              git pull
              git push -f
          } else {
              Write-Output "did-update=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
              Write-Host "No changes to commit for Win32Metadata"
              exit 0
          }

  docs:
    name: Update Win32Docs
    runs-on: windows-latest
    outputs:
      version: ${{ steps.commit-docs.outputs.version }}
      did-update: ${{ steps.commit-docs.outputs.did-update }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        shell: pwsh
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git config --local push.autoSetupRemote true
          git config --local push.default upstream

      - name: Download Win32Docs
        shell: pwsh
        run: ./scripts/Get-Win32Docs.ps1

      - name: Commit and Push Changes
        id: commit-docs
        shell: pwsh
        run: |
          $version = (Get-Content ./metadata/Microsoft.Windows.SDK.Win32Docs.version -Raw).Trim()
          $branchName = "update-win32docs-$version"

          Write-Output "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

          git add ./metadata/*.msgpack
          git add ./metadata/*.version

          if (-not (git diff-index --quiet HEAD --)) {
              Write-Output "did-update=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

              git commit -m "Update Win32Docs to $version"
              git pull
              git push -f
          } else {
              Write-Output "did-update=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append              
              Write-Host "No changes to commit for Win32Docs"
              exit 0
          }
